name: K6 Load Testing

on:
  workflow_dispatch:    

jobs:
  load-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install k6
        run: |
          sudo apt-get update
          sudo apt-get install k6

      - name: Run load test
        run: |
          k6 run src/client-registration-and-login-bdd-test.ts
